#!/bin/bash
cat << EOF
".---------------------------------------------------------------------------.\n"
'|                                                         [ Warung Lite v0,0 ]'
'|                                                         / / / / / / / / / /|'
'|                __________________________                 6°               |'
'|  warung ..    |                          |                                 |'
'|    ((|))      |                          |                                 |'
'|    //|\\\      |                       ___|                                 |'
'|   ///|\\\\\\     |          ______///////   |                                 |'
'|  ////|\\\\\\\\    |___///////                |               /////////////////\|'
'|  |\/\/\/\|    |                          |              //////////////////\\|'
'|  |/\/\/\/|    |                          |             /|/\/\/\/\/\/\/\/||||'
'|./________.\___|  disingkat wr.           |__    ____ |\/|/\/\/\/\/\/\/\/||||'
'|/\/\/\/\/\/\/\/|  • ° ××××××××××××××××××××||  __/     /\/|/\/\/\/\/\/\/\/||||'
'|||||||||||||||||[||]..___________________.||..________|||||||||||||||||||||||'
==============================================================================∆
EOF

if [ -e $PWD/.data/.wr/sheet/* ]
then
if [ -d $PWD/.data/.wr/sheet ]
then
cat  $PWD/.data/.wr/sheet/*

read -r -p "[ remv / no-default ] " func

case $func in
remv)
rm -rf .data/.wr
;;
*)
clear
bash warung
;;
esac
fi
else
echo "[crt/y]:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::[•v•]"
echo "[+stock+]"
read -r -p "[ stock / no-default ] " altw
case $altw in
stock )
if [ ! -d .data/.wr/sheet ]
then
 mkdir -p .data/.wr/sheet
 chmod 755 .data/.wr
fi
read -r -p "[:-_] \0-9/ × input type number  .×. [ N° ] COLUMN .-> " coluy
read -r -p "[:-_] \0-9/ × input type number  .×. [ N° ] ROW .-> " rowe

clear

x=0
y=0

echo -en "[ :: stock ][°-°\°|°/°-°] day stock sheet [ COLUMN/ROW [ $coluy/$rowe ] ] \n" >> $PWD/.data/.wr/sheet/stock
echo -en "::" >> $PWD/.data/.wr/sheet/stock

while [ $x -ne $coluy ]; do
if [[ $x -lt $coluy ]]
 then
 if [[ $coluy -gt $coluy ]]
  then
   echo -n ""
 fi
 x=$((x + 1))
 column=$((x))
 echo -en "  $column   " >> $PWD/.data/.wr/sheet/stock
fi
done
while [[ $y -ne $rowe ]]; do
if [[ $y -le $rowe ]]
 then
  y=$((y + 1))
  row=$((y))
  echo -en "$row\n\n" >> $PWD/.data/.wr/sheet/stock
fi
done
;;
*)
clear
bash warung
;;
esac
fi
