#!/bin/bash/

init_() {
 echo "::.. ABcDefGhIjKlmNoPqRsTufWxyZ ~ 1234567890 RANDOM -v- "
 echo "1) Alphanum.. 32 Character (upper and lowercase)"
 echo "2) Alphanum.. 64 Character (upper and lowercase)"
 echo "3) Alphanum.. 32 Character (lowercase only)"
 echo "...      "
 rndm_it(){
 read -r -p "enter the number: " numopt
 case $numopt in
 1)
 # ONE ONLY
 ALPHA_NUM=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
 echo $ALPHA_NUM
 if [ "$ALPHA_NUM" == "" ];
  then
  echo  ALPHA_NUM=0
 fi
 ;;
 2)
 # TWO 1+1 ::TWOAGAPATS
 ALPHA_NUM=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)
 echo $ALPHA_NUM
 if [ "$ALPHA_NUM" == "" ];
  then
   echo  ALPHA_NUM=0
 fi
 ;;
 3)
 ALPHA_NUM=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 32 | head -n 1)
 echo $ALPHA_NUM
 if [ "$ALPHA_NUM" == "" ];
  then
  echo  ALPHA_NUM=0
 fi
 ;;
 *)
 clear; wait; init_; echo exit;;
 esac
 rndm_it
 }
 rndm_it
}
init_
