#!/bin/bash
read -r -p "[::_] [calc] × first input type of number here .. .×. \0-9/ .-> " n1
echo "::  [ "$n1" ]::result pick ... "
echo "::  [add]  + addition        ::/+"
echo "::  [sub]  - substraction    ::/-"
echo "::  [div]  / dvision         ::/÷"
echo "::  [mlt]  * multiplication  ::/*"
read -r -p "[+/-/÷/*] × select typeof .-> " calc
read -r -p "[::_] $n1 $calc input next typeof number to get.result .-> " n2
case $calc in
   add) echo "$n1 + $n2 = $(($n1 + $n2))"
   ;;
   sub) echo "$n1 - $n2 = $(($n1 - $n2))"
   ;;
   div) echo "$n1 / $n2 = $(($n1 / $n2))"
   ;;
   mlt) echo "$n1 * $n2 = $(($n1 * $n2))"
   ;;
esac
